/**
 * Tool Registry & Server-Side Authorization.
 *
 * Maintains registered AI tools and enforces static capability checks
 * before model-invoked execution.
 */

import 'server-only';

import type { AIToolDefinition } from '@/services/ai/ai-provider.interface';
import type { AITenantContext } from '../context';
import { zodToJsonSchema } from './schema-converter';
import type { AITool } from './tool-contract';

export interface ToolAuthorizationResult {
  authorized: boolean;
  tool?: AITool;
  reason?: string;
}

export class ToolRegistry {
  private readonly tools = new Map<string, AITool>();

  /**
   * Registers a new AI tool. Throws if a tool with the same name already exists.
   */
  register(tool: AITool): this {
    if (this.tools.has(tool.name)) {
      throw new Error(`Tool already registered: ${tool.name}`);
    }
    this.tools.set(tool.name, tool);
    return this;
  }

  /**
   * Retrieves a tool by name.
   */
  get(name: string): AITool | undefined {
    return this.tools.get(name);
  }

  /**
   * Checks if a tool is registered.
   */
  has(name: string): boolean {
    return this.tools.has(name);
  }

  /**
   * Returns all registered tools.
   */
  list(): AITool[] {
    return Array.from(this.tools.values());
  }

  /**
   * Clears all registered tools (used primarily in tests).
   */
  clear(): void {
    this.tools.clear();
  }

  /**
   * Returns normalized tool definitions for providers, filtered to only those
   * tools authorized by the given capabilities set.
   */
  getDefinitionsForCapabilities(capabilities: ReadonlySet<string>): AIToolDefinition[] {
    const definitions: AIToolDefinition[] = [];

    for (const tool of this.tools.values()) {
      if (capabilities.has(tool.capabilityRequired)) {
        definitions.push({
          name: tool.name,
          description: tool.description,
          inputSchema: zodToJsonSchema(tool.inputSchema),
        });
      }
    }

    return definitions;
  }

  /**
   * Authorizes a tool call against the server-verified AITenantContext.
   *
   * NEVER trust permission assertions or capabilities generated by the model.
   */
  authorize(ctx: AITenantContext, toolName: string): ToolAuthorizationResult {
    const tool = this.tools.get(toolName);
    if (!tool) {
      return {
        authorized: false,
        reason: `Unknown or unregistered tool: ${toolName}`,
      };
    }

    if (!ctx.capabilities.has(tool.capabilityRequired)) {
      return {
        authorized: false,
        tool,
        reason: `AI execution context lacks required capability "${tool.capabilityRequired}" for tool "${toolName}"`,
      };
    }

    return {
      authorized: true,
      tool,
    };
  }
}

/** Global default singleton tool registry */
export const defaultToolRegistry = new ToolRegistry();
