/**
 * Identifier and slug generation.
 *
 * Primary keys are UUIDs generated by the database, so nothing here mints them.
 * These are the human-facing identifiers: workspace slugs, order numbers,
 * request ids.
 */

import { randomBytes, randomUUID } from 'node:crypto';

/** For request correlation in logs. Not security-sensitive, but cheap to make
 *  unguessable, so there is no reason not to. */
export function requestId(): string {
  return randomUUID();
}

/**
 * URL-safe slug from arbitrary text. Diacritics are decomposed and stripped so
 * that "Café Karachi" becomes "cafe-karachi" rather than losing the word.
 */
export function slugify(input: string): string {
  return input
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
}

const SLUG_SUFFIX_ALPHABET = 'abcdefghijkmnpqrstuvwxyz23456789';

/**
 * Random suffix used to resolve a slug collision. The alphabet omits `l`, `o`,
 * `0` and `1` because workspace slugs appear in URLs that people read aloud and
 * retype.
 */
export function slugSuffix(length = 5): string {
  const bytes = randomBytes(length);
  let output = '';
  for (const byte of bytes) {
    output += SLUG_SUFFIX_ALPHABET[byte % SLUG_SUFFIX_ALPHABET.length];
  }
  return output;
}

/**
 * Builds a candidate slug, falling back to a generated name when the input
 * reduces to nothing — a workspace named only with emoji or non-Latin script
 * would otherwise produce an empty slug and a unique-constraint violation.
 */
export function workspaceSlug(name: string): string {
  const base = slugify(name);
  return base === '' ? `workspace-${slugSuffix()}` : base;
}

/**
 * Order numbers are what a customer reads back over WhatsApp, so they are short,
 * unambiguous, and never sequential-looking enough to invite guessing at a
 * competitor's volume.
 *
 * Format: `<prefix>-<yy><mm>-<sequence padded to 4>`, e.g. `AF-2608-0042`.
 * The sequence is per workspace and per month, supplied by the caller inside the
 * same transaction that writes the order, so two concurrent orders cannot share
 * a number.
 */
export function formatOrderNumber(prefix: string, date: Date, sequence: number): string {
  const yy = String(date.getUTCFullYear()).slice(-2);
  const mm = String(date.getUTCMonth() + 1).padStart(2, '0');
  const seq = String(sequence).padStart(4, '0');
  return `${prefix.toUpperCase()}-${yy}${mm}-${seq}`;
}

/**
 * Derives the order-number prefix from a business name: initials for multi-word
 * names, first three letters otherwise. "Akmal Fashion" gives "AF"; "Zaiqa"
 * gives "ZAI".
 */
export function orderNumberPrefix(businessName: string): string {
  const words = businessName
    .split(/\s+/)
    .map((word) => word.replace(/[^A-Za-z]/g, ''))
    .filter((word) => word.length > 0);

  if (words.length >= 2) {
    return words
      .slice(0, 3)
      .map((word) => word[0]!.toUpperCase())
      .join('');
  }
  if (words.length === 1) {
    return words[0]!.slice(0, 3).toUpperCase();
  }
  return 'ORD';
}
