/**
 * Orders, order items, and order events.
 *
 * Every function takes `workspaceId` and puts it in the `where` clause. Writes use
 * `updateMany` with the scope in the filter rather than `update` by id, because
 * `update` ignores the filter and would happily edit another tenant's row; a count of
 * zero is what the service turns into `NotFoundError`.
 *
 * Order numbers are human-facing sequential identifiers per workspace and per month,
 * generated by reading the max sequence from the current month and incrementing it.
 * The unique constraint on `orderNumber` prevents two concurrent creates from sharing
 * a number even if they read the same max.
 *
 * Orders are soft-deleted. A deleted order stays in the database because it already
 * affected inventory, contact aggregates, and analytics — erasing it would corrupt
 * the counts that the business uses to understand their operation.
 */

import 'server-only';

import type { Db } from '@/db/prisma';
import { formatOrderNumber, orderNumberPrefix } from '@/lib/ids';
import type {
  FulfillmentStatus,
  OrderStatus,
  PaymentMethod,
  PaymentStatus,
} from '@/server/validation/order';

export type OrderRow = {
  id: string;
  workspaceId: string;
  orderNumber: string;
  contactId: string;
  conversationId: string | null;
  status: OrderStatus;
  paymentStatus: PaymentStatus;
  fulfillmentStatus: FulfillmentStatus;
  currency: string;
  subtotalMinor: number;
  discountMinor: number;
  deliveryFeeMinor: number;
  taxMinor: number;
  totalMinor: number;
  paymentMethod: PaymentMethod;
  customerName: string;
  phoneE164: string;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  postalCode: string | null;
  country: string;
  notes: string | null;
  createdByMemberId: string | null;
  createdByAi: boolean;
  aiAgentId: string | null;
  placedAt: Date;
  confirmedAt: Date | null;
  shippedAt: Date | null;
  deliveredAt: Date | null;
  cancelledAt: Date | null;
  cancelReason: string | null;
  courierName: string | null;
  trackingNumber: string | null;
  createdAt: Date;
  updatedAt: Date;
};

const ORDER_SELECT = {
  id: true,
  workspaceId: true,
  orderNumber: true,
  contactId: true,
  conversationId: true,
  status: true,
  paymentStatus: true,
  fulfillmentStatus: true,
  currency: true,
  subtotalMinor: true,
  discountMinor: true,
  deliveryFeeMinor: true,
  taxMinor: true,
  totalMinor: true,
  paymentMethod: true,
  customerName: true,
  phoneE164: true,
  addressLine1: true,
  addressLine2: true,
  city: true,
  postalCode: true,
  country: true,
  notes: true,
  createdByMemberId: true,
  createdByAi: true,
  aiAgentId: true,
  placedAt: true,
  confirmedAt: true,
  shippedAt: true,
  deliveredAt: true,
  cancelledAt: true,
  cancelReason: true,
  courierName: true,
  trackingNumber: true,
  createdAt: true,
  updatedAt: true,
} as const;

export type OrderItemRow = {
  id: string;
  workspaceId: string;
  orderId: string;
  productId: string | null;
  variantId: string | null;
  nameSnapshot: string;
  skuSnapshot: string | null;
  variantSnapshot: string | null;
  unitPriceMinor: number;
  quantity: number;
  lineSubtotalMinor: number;
  createdAt: Date;
};

const ORDER_ITEM_SELECT = {
  id: true,
  workspaceId: true,
  orderId: true,
  productId: true,
  variantId: true,
  nameSnapshot: true,
  skuSnapshot: true,
  variantSnapshot: true,
  unitPriceMinor: true,
  quantity: true,
  lineSubtotalMinor: true,
  createdAt: true,
} as const;

export type OrderEventRow = {
  id: string;
  workspaceId: string;
  orderId: string;
  type: string;
  fromStatus: OrderStatus | null;
  toStatus: OrderStatus | null;
  actorMemberId: string | null;
  byAi: boolean;
  note: string | null;
  createdAt: Date;
};

const ORDER_EVENT_SELECT = {
  id: true,
  workspaceId: true,
  orderId: true,
  type: true,
  fromStatus: true,
  toStatus: true,
  actorMemberId: true,
  byAi: true,
  note: true,
  createdAt: true,
} as const;

export type OrderListRow = OrderRow & {
  contactName: string | null;
  itemCount: number;
};

export type OrderDetailRow = OrderRow & {
  contactName: string | null;
  items: OrderItemRow[];
  events: OrderEventRow[];
};

export type OrderFilters = {
  search: string | null;
  status?: OrderStatus;
  paymentStatus?: PaymentStatus;
  fulfillmentStatus?: FulfillmentStatus;
  contactId?: string;
  cursor?: string;
  limit: number;
};

export type OrderPage = {
  rows: OrderListRow[];
  nextCursor: string | null;
};

/**
 * Builds the tenant-scoped filter for a list query.
 */
function buildWhere(
  workspaceId: string,
  filters: OrderFilters,
): Record<string, unknown> {
  const where: Record<string, unknown> = { workspaceId, deletedAt: null };

  if (filters.status) where.status = filters.status;
  if (filters.paymentStatus) where.paymentStatus = filters.paymentStatus;
  if (filters.fulfillmentStatus) where.fulfillmentStatus = filters.fulfillmentStatus;
  if (filters.contactId) where.contactId = filters.contactId;

  if (filters.search) {
    const term = filters.search;
    where.OR = [
      { orderNumber: { contains: term, mode: 'insensitive' } },
      { customerName: { contains: term, mode: 'insensitive' } },
      { phoneE164: { contains: term } },
      { city: { contains: term, mode: 'insensitive' } },
    ];
  }

  return where;
}

/**
 * One page of orders, newest first.
 */
export async function listOrders(
  db: Db,
  workspaceId: string,
  filters: OrderFilters,
): Promise<OrderPage> {
  const rows = await db.order.findMany({
    where: buildWhere(workspaceId, filters),
    select: {
      ...ORDER_SELECT,
      contact: { select: { name: true } },
      _count: { select: { items: true } },
    },
    orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
    take: filters.limit + 1,
    ...(filters.cursor ? { cursor: { id: filters.cursor }, skip: 1 } : {}),
  });

  const hasMore = rows.length > filters.limit;
  const page = hasMore ? rows.slice(0, filters.limit) : rows;

  return {
    rows: page.map(({ contact, _count, ...order }) => ({
      ...(order as OrderRow),
      contactName: contact?.name ?? null,
      itemCount: _count.items,
    })),
    nextCursor: hasMore ? (page[page.length - 1]?.id ?? null) : null,
  };
}

export async function findOrderById(
  db: Db,
  workspaceId: string,
  orderId: string,
): Promise<OrderRow | null> {
  const row = await db.order.findFirst({
    where: { id: orderId, workspaceId, deletedAt: null },
    select: ORDER_SELECT,
  });
  return (row as OrderRow | null) ?? null;
}

/**
 * The order with items and events for the detail page.
 */
export async function findOrderDetail(
  db: Db,
  workspaceId: string,
  orderId: string,
): Promise<OrderDetailRow | null> {
  const row = await db.order.findFirst({
    where: { id: orderId, workspaceId, deletedAt: null },
    select: {
      ...ORDER_SELECT,
      contact: { select: { name: true } },
      items: { select: ORDER_ITEM_SELECT },
      events: { select: ORDER_EVENT_SELECT, orderBy: { createdAt: 'asc' } },
    },
  });
  if (!row) return null;

  const { contact, items, events, ...order } = row;
  return {
    ...(order as OrderRow),
    contactName: contact?.name ?? null,
    items: items as OrderItemRow[],
    events: events as OrderEventRow[],
  };
}

export async function findOrderByNumber(
  db: Db,
  workspaceId: string,
  orderNumber: string,
): Promise<OrderRow | null> {
  const row = await db.order.findFirst({
    where: { workspaceId, orderNumber, deletedAt: null },
    select: ORDER_SELECT,
  });
  return (row as OrderRow | null) ?? null;
}

/**
 * Generates the next order number for the workspace.
 *
 * Format: `<prefix>-<yy><mm>-<sequence>`, e.g. `AF-2608-0042`.
 * The sequence is per workspace and per month. Called inside the same transaction
 * that writes the order, so two concurrent orders cannot share a number even if
 * they read the same max.
 */
export async function generateOrderNumber(
  db: Db,
  workspaceId: string,
  businessName: string,
  date: Date,
): Promise<string> {
  const year = date.getUTCFullYear();
  const month = date.getUTCMonth() + 1;

  // Start and end of the current month in UTC
  const monthStart = new Date(Date.UTC(year, month - 1, 1, 0, 0, 0, 0));
  const monthEnd = new Date(Date.UTC(year, month, 1, 0, 0, 0, 0));

  // Find the highest sequence in this workspace for this month
  const lastOrder = await db.order.findFirst({
    where: {
      workspaceId,
      createdAt: { gte: monthStart, lt: monthEnd },
    },
    select: { orderNumber: true },
    orderBy: { createdAt: 'desc' },
  });

  let sequence = 1;
  if (lastOrder) {
    // Extract sequence from the order number (e.g., "AF-2608-0042" → 42)
    const parts = lastOrder.orderNumber.split('-');
    if (parts.length === 3) {
      const lastSeq = Number.parseInt(parts[2] ?? '0', 10);
      if (!Number.isNaN(lastSeq)) {
        sequence = lastSeq + 1;
      }
    }
  }

  const prefix = orderNumberPrefix(businessName);
  return formatOrderNumber(prefix, date, sequence);
}

export type OrderWriteFields = {
  orderNumber: string;
  contactId: string;
  conversationId: string | null;
  status: OrderStatus;
  paymentStatus: PaymentStatus;
  fulfillmentStatus: FulfillmentStatus;
  currency: string;
  subtotalMinor: number;
  discountMinor: number;
  deliveryFeeMinor: number;
  taxMinor: number;
  totalMinor: number;
  paymentMethod: PaymentMethod;
  customerName: string;
  phoneE164: string;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  postalCode: string | null;
  country: string;
  notes: string | null;
  createdByMemberId: string | null;
  createdByAi: boolean;
  aiAgentId: string | null;
};

export type OrderItemWriteFields = {
  productId: string | null;
  variantId: string | null;
  nameSnapshot: string;
  skuSnapshot: string | null;
  variantSnapshot: string | null;
  unitPriceMinor: number;
  quantity: number;
  lineSubtotalMinor: number;
};

export async function createOrder(
  db: Db,
  input: OrderWriteFields & { workspaceId: string },
  items: OrderItemWriteFields[],
): Promise<OrderRow> {
  const row = await db.order.create({
    data: {
      ...input,
      items: {
        create: items.map((item) => ({
          workspaceId: input.workspaceId,
          ...item,
        })),
      },
    },
    select: ORDER_SELECT,
  });
  return row as OrderRow;
}

export async function updateOrder(
  db: Db,
  workspaceId: string,
  orderId: string,
  data: Partial<OrderWriteFields>,
): Promise<number> {
  const result = await db.order.updateMany({
    where: { id: orderId, workspaceId, deletedAt: null },
    data,
  });
  return result.count;
}

export async function softDeleteOrder(
  db: Db,
  workspaceId: string,
  orderId: string,
  at: Date,
): Promise<number> {
  const result = await db.order.updateMany({
    where: { id: orderId, workspaceId, deletedAt: null },
    data: { deletedAt: at },
  });
  return result.count;
}

export async function countOrders(db: Db, workspaceId: string): Promise<number> {
  return db.order.count({ where: { workspaceId, deletedAt: null } });
}

export async function countOrdersByStatus(
  db: Db,
  workspaceId: string,
): Promise<Record<string, number>> {
  const groups = await db.order.groupBy({
    by: ['status'],
    where: { workspaceId, deletedAt: null },
    _count: { _all: true },
  });

  const counts: Record<string, number> = {};
  for (const group of groups) {
    counts[group.status] = group._count._all;
  }
  return counts;
}

// ── Order Events ───────────────────────────────────────────────────────────

export type OrderEventWriteFields = {
  type: string;
  fromStatus: OrderStatus | null;
  toStatus: OrderStatus | null;
  actorMemberId: string | null;
  byAi: boolean;
  note: string | null;
};

export async function createOrderEvent(
  db: Db,
  input: OrderEventWriteFields & { workspaceId: string; orderId: string },
): Promise<OrderEventRow> {
  const row = await db.orderEvent.create({
    data: input,
    select: ORDER_EVENT_SELECT,
  });
  return row as OrderEventRow;
}

export async function listOrderEvents(
  db: Db,
  workspaceId: string,
  orderId: string,
): Promise<OrderEventRow[]> {
  const rows = await db.orderEvent.findMany({
    where: { workspaceId, orderId },
    select: ORDER_EVENT_SELECT,
    orderBy: { createdAt: 'asc' },
  });
  return rows as OrderEventRow[];
}
